### ISSUE TITLE
Exception in thread "main" java.lang.NullPointerException

### ISSUE THREAD

**Issue by Axure** [jahewson/sfntly#11]
`java -jar ~/Coding/sfntly/java/dist/tools/sfnttool/sfnttool.jar -w -s 'ws' ./NotoSansCJKsc-Light.otf ./noto.otf`

> Exception in thread "main" java.lang.NullPointerException
>     at com.google.typography.font.tools.sfnttool.GlyphCoverage.getGlyph(Unknown Source)
>     at com.google.typography.font.tools.sfnttool.GlyphCoverage.touchGlyph(Unknown Source)
>     at com.google.typography.font.tools.sfnttool.GlyphCoverage.getGlyphCoverage(Unknown Source)
>     at com.google.typography.font.tools.sfnttool.SfntTool.subsetFontFile(Unknown Source)
>     at com.google.typography.font.tools.sfnttool.SfntTool.main(Unknown Source)

`java -version`

> java version "1.8.0_45"
> Java(TM) SE Runtime Environment (build 1.8.0_45-b14)
> Java HotSpot(TM) 64-Bit Server VM (build 25.45-b02, mixed mode)

OS X 10.11Beta(15A278b)

**Comment by jahewson** [comment]
This error occurs because .otf files aren't supported by sfntly. More specifically, fonts which use a "CFF" table. Arguably there should be a better error message, but until Google adds CFF support there's nothing that can be done here.
